In [6]:
import numpy as np
from tnmp.tnmp import Clause

In [11]:
clause = Clause([0,1], [0,1], "c0")

In [12]:
data_tc = np.ones([2] * len(clause.pos))
sl = tuple(1 if clause(p) else 0 for p in clause.pos)
data_tc[sl] = 0

double_tensor = np.kron(data_tc, data_tc)

In [13]:
double_tensor.shape

(4, 4)

In [27]:
d = {
    "00": 0,
    "01": 1,
    "10": 2,
    "11": 3,
}
double_tensor[d["00"],d["10"]]

0.0

In [50]:
zero = np.array([1, 0])
one = np.array([0, 1])

double_tensor @ np.kron(zero, zero)

array([1., 1., 1., 1.])

In [44]:
zero.T @ data_tc @ one

0.0

In [38]:
data_tc

array([[1., 0.],
       [1., 1.]])

In [51]:
np.kron(zero, zero)

array([1, 0, 0, 0])

In [52]:
np.kron(one, one)

array([0, 0, 0, 1])

In [53]:
np.kron(np.eye(2), np.eye(2))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
a = np.random.rand(100)

In [56]:
np.linalg.norm(a, ord=1.0) - sum(abs(a))

-1.4210854715202004e-14

In [57]:
sum(abs(a))

47.29664691362037

In [58]:
np.linalg.norm(a, ord=1.0) 

47.29664691362036